In [2]:
import numpy as np
import pandas as pd

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
names = pd.read_table('mimic_synthetic_feat.name',sep='\n',header=None)

C:\Users\B.K Goel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

FileNotFoundError: [Errno 2] File b'mimic_synthetic_feat.name' does not exist: b'mimic_synthetic_feat.name'

In [4]:
name_col = names[0].tolist()

In [5]:
name_col

['SUBJECT_ID',
 'HADM_ID',
 'ADMITTIME',
 'DISCHTIME',
 'INSURANCE',
 'LANGUAGE',
 'RELIGION',
 'MARITAL_STATUS',
 'ETHNICITY',
 'GENDER',
 'AGE',
 'HR_MIN_DAY1',
 'HR_MAX_DAY1',
 'HR_MEAN_DAY1',
 'SYS_BP_MIN_DAY1',
 'SYS_BP_MAX_DAY1',
 'SYS_BP_MEAN_DAY1',
 'DIAS_BP_MIN_DAY1',
 'DIAS_BP_MAX_DAY1',
 'DIAS_BP_MEAN_DAY1',
 'MEAN_BP_MIN_DAY1',
 'MEAN_BP_MAX_DAY1',
 'MEAN_BP_MEAN_DAY1',
 'RESP_RATE_MIN_DAY1',
 'RESP_RATE_MAX_DAY1',
 'RESP_RATE_MEAN_DAY1',
 'TEMP_MIN_DAY1',
 'TEMP_MAX_DAY1',
 'TEMP_MEAN_DAY1',
 'SPO2_MIN_DAY1',
 'SPO2_MAX_DAY1',
 'SPO2_MEAN_DAY1',
 'GLUCOSE_MIN_DAY1',
 'GLUCOSE_MAX_DAY1',
 'GLUCOSE_MEAN_DAY1',
 'HR_MIN_DAY2',
 'HR_MAX_DAY2',
 'HR_MEAN_DAY2',
 'SYS_BP_MIN_DAY2',
 'SYS_BP_MAX_DAY2',
 'SYS_BP_MEAN_DAY2',
 'DIAS_BP_MIN_DAY2',
 'DIAS_BP_MAX_DAY2',
 'DIAS_BP_MEAN_DAY2',
 'MEAN_BP_MIN_DAY2',
 'MEAN_BP_MAX_DAY2',
 'MEAN_BP_MEAN_DAY2',
 'RESP_RATE_MIN_DAY2',
 'RESP_RATE_MAX_DAY2',
 'RESP_RATE_MEAN_DAY2',
 'TEMP_MIN_DAY2',
 'TEMP_MAX_DAY2',
 'TEMP_MEAN_DAY2',
 'SPO2_MIN_DAY2',
 'SPO2_MAX_DAY2',
 'SPO2_MEAN_DAY2',
 'GLUCOSE_MIN_DAY2',
 'GLUCOSE_MAX_DAY2',
 'GLUCOSE_MEAN_DAY2',
 'ICU',
 'Tuberculosis',
 'Immuniz/scrn',
 'AcuteMI',
 'Coronathero',
 'Chestpain',
 'Pulmhartdx',
 'Othheartdx',
 'Conduction',
 'Dysrhythmia',
 'Cardiaarrst',
 'chf;nonhp',
 'AcuteCVD',
 'Hd/nckcancr',
 'Precereoccl',
 'OtherCVD',
 'TIA',
 'LateeffCVD',
 'Peripathero',
 'Aneurysm',
 'Artembolism',
 'Otcirculdx',
 'Phlebitis',
 'Varicosevn',
 'Esophcancer',
 'Hemmorhoids',
 'Othveindx',
 'Pneumonia',
 'Influenza',
 'Tonsillitis',
 'Bronchitis',
 'Otuprspin',
 'COPD',
 'Asthma',
 'Asppneumon',
 'Stomchcancr',
 'Pleurisy',
 'Adltrespfl',
 'Lungexternl',
 'Othlowresp',
 'Otupprresp',
 'Intestinfct',
 'Teethdx',
 'Mouthdx',
 'Esophgealdx',
 'Gasduoulcer',
 'Coloncancer',
 'Gastritis',
 'Otdxstomch',
 'Appendicitis',
 'Abdomhernia',
 'Ulceratcol',
 'Intobstruct',
 'Diverticulos',
 'Anal/rectal',
 'Peritonitis',
 'Biliarydx',
 'Rctm/anusca',
 'Othliverdx',
 'Pancreasdx',
 'GIhemorrhag',
 'Gastroent',
 'OtherGIdx',
 'Nephritis',
 'Acrenlfail',
 'Chrrenfail',
 'UTI',
 'Liver/ibdca',
 'Urinstone',
 'Otdxkidney',
 'Otdxbladdr',
 'OtherGUdx',
 'BPH',
 'Infmalegen',
 'Othmalegen',
 'Breastdx',
 'PID',
 'Endometrios',
 'Pancreascan',
 'Prolapse',
 'Menstrualdx',
 'Ovariancyst',
 'Menopausldx',
 'Feminfertil',
 'Otfemalgen',
 'Contraceptiv',
 'Spontabortn',
 'Inducabortn',
 'Abortcompl',
 'GI/peritcan',
 'Ectopicpreg',
 'Otpregcomp',
 'Hemorrpreg',
 'HTNinpreg',
 'Earlylabor',
 'Longpregncy',
 'DMinpreg',
 'Malposition',
 'Pelvicobstr',
 'Prevc-sectn',
 'Brnch/lngca',
 'Fetaldistrs',
 'Amniosdx',
 'Umbilcord',
 'OB-relatedperintrauma',
 'Otcomplbir',
 'Nmlpreg/del',
 'Skininfectn',
 'Otinflskin',
 'Ulcerskin',
 'Septicemia',
 'Otrespirca',
 'Othskindx',
 'Infectarth',
 'Rheumarth',
 'Osteoarthros',
 'Otjointdx',
 'Backproblem',
 'Osteoporosis',
 'Pathologfx',
 'Acqfootdef',
 'Otacqdefor',
 'Bone/ctcncr',
 'SLE',
 'Otconntiss',
 'Otbonedx',
 'Cardiacanom',
 'GIconganom',
 'guconganom',
 'Nervcongan',
 'Otconganom',
 'Liveborn',
 'Lowbirthwt',
 'Skinmelanom',
 'Birthasphyx',
 'Respdistres',
 'Perintjaund',
 'Birthtrauma',
 'Otperintdx',
 'Jointinjury',
 'Fxhip',
 'Spincorinj',
 'Fxskullfac',
 'Fxarm',
 'Non-epithca',
 'Fxleg',
 'Othfracture',
 'Sprain',
 'Intracrninj',
 'Crushinjury',
 'Opnwndhead',
 'Opnwndextr',
 'Complicdevi',
 'Complicproc',
 'Superficinj',
 'Breastcancr',
 'Burns',
 'Poisonpsych',
 'Poisnotmed',
 'Poisnnonmed',
 'Otherinjury',
 'Syncope',
 'FUO',
 'Lymphenlarg',
 'Gangrene',
 'Shock',
 'Uteruscancr',
 'Nausea/vomit',
 'Abdomnlpain',
 'Fatigue',
 'Allergy',
 'Socialadmin',
 'Exam/eval',
 'Otaftercare',
 'Otherscreen',
 'Unclassified',
 'Cervixcancr',
 'ECodes:Cut/pierce',
 'ECodes:Drowning/submersion',
 'ECodes:Fall',
 'ECodes:Fire/burn',
 'ECodes:Firearm',
 'ECodes:Machinery',
 'ecodes:motorvehicletraffic(mvt)',
 'ECodes:Pedalcyclist-notMVT',
 'ECodes:Pedestrian-notMVT',
 'ecodes:transport-notmvt',
 'ECodes:Natural/environment',
 'ECodes:Overexertion',
 'ECodes:Poisoning',
 'ECodes:Struckby-against',
 'ECodes:Suffocation',
 'ECodes:Adverseeffectsofmedicalcare',
 'ECodes:Adverseeffectsofmedicaldrugs',
 'ECodes:Otherspecifiedandclassifiable',
 'ecodes:otherspecified-nec',
 'ECodes:Unspecified',
 'ECodes:Placeofoccurrence',
 'Ovarycancer',
 'Femgenitca',
 'Prostatecan',
 'Othbactinf',
 'Testiscancr',
 'Malgenitca',
 'Bladdercncr',
 'Kidny/rnlca',
 'Urinyorgca',
 'Brain/nscan',
 'Thyroidcncr',
 'Hodgkin-sds',
 'Non-Hodglym',
 'Leukemias',
 'Mycoses',
 'Multmyeloma',
 'Otprimryca',
 '2ndarymalig',
 'Maligneopls',
 'Neoplsmunsp',
 'Maintchem/r',
 'Bnignutneo',
 'Otbnignneo',
 'Thyroiddsor',
 'DiabMelnoc',
 'HIVinfectn',
 'DiabMelw/cm',
 'Otendodsor',
 'Nutritdefic',
 'Hyperlipidem',
 'Gout/otcrys',
 'Fluid/elcdx',
 'Cysticfibro',
 'Immunitydx',
 'Otnutritdx',
 'Anemia',
 'Hepatitis',
 'Acutp-hanm',
 'Sicklecell',
 'Coag/hemrdx',
 'Whtblooddx',
 'Othematldx',
 'Adjustmentdisorders',
 'Anxietydisorders',
 'Attention-deficit/conduct/disruptivebeha',
 'Delirium/dementia/amnestic/othercognitiv',
 'Developmentaldisorders',
 'Disordersusuallydiagnosedininfancy/ch',
 'ImpulsecontroldisordersNEC',
 'Mooddisorders',
 'Personalitydisorders',
 'Schizophreniaandotherpsychoticdisorde',
 'Alcohol-relateddisorders',
 'Substance-relateddisorders',
 'Suicideandintentionalself-inflictedin',
 'Screeningandhistoryofmentalhealthan',
 'Miscellaneousmentaldisorders',
 'Viralinfect',
 'Meningitis',
 'Encephalitis',
 'OthCNSinfx',
 'Parkinson-s',
 'Othinfectns',
 'MS',
 'OtheredCNS',
 'Paralysis',
 'Epilepsy/cnv',
 'Headache/mig',
 'Coma/brndmg',
 'Cataract',
 'Retinaldx',
 'Glaucoma',
 'Blindness',
 'SexualInfxs',
 'Eyeinfectn',
 'Othereyedx',
 'Otitismedia',
 'Dizziness',
 'Othereardx',
 'Othnervdx',
 'Hrtvalvedx',
 'Carditis',
 'HTN',
 'Htncomplicn']

In [6]:
data = pd.read_table('mimic_synthetic_train.data',sep=' ',header=None)

C:\Users\B.K Goel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [7]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,332,333,334,335,336,337,338,339,340,341
0,0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,...,0,0,0,0,0,0.0,0,0,0,0
1,1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,...,0,0,0,0,0,0.0,0,0,0,1
2,2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,...,0,0,0,0,0,0.0,0,0,0,0
3,3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,...,0,0,0,0,0,0.0,0,0,1,0
4,4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,...,0,0,0,0,0,0.0,0,0,0,0

In [8]:
data.drop(0,axis=1,inplace=True)

In [9]:
data

,1,2,3,4,5,6,7,8,9,10,...,332,333,334,335,336,337,338,339,340,341
0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0,0.0,0,0,0,0
3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0,0.0,0,0,0,0
5,11634,144424,2147-08-30_19:51:00,2136-11-19_18:53:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
6,9259,189252,2144-04-26_22:49:00,2199-06-24_10:49:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
7,43732,128084,2194-04-12_01:19:00,2118-09-30_19:00:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,0
8,17978,167487,2159-10-13_23:08:00,2179-09-14_15:40:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
9,25610,151971,2119-08-01_07:15:00,2141-09-26_13:15:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
10,1999,144515,2171-09-11_15:27:00,2153-02-20_18:00:00,Medicare,SPAN,PROTESTANT_QUAKER,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,1
11,20651,177259,2145-02-17_17:20:00,2107-09-16_04:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
12,25707,123780,2110-09-17_22:22:00,2198-09-18_16:14:00,Medicare,ENGL,PROTESTANT_QUAKER,DIVORCED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
13,29887,171410,2192-10-13_18:24:00,2193-05-24_15:25:00,Self_Pay,SPAN,PROTESTANT_QUAKER,SINGLE,HISPANIC/LATINO_-_GUATEMALAN,F,...,0,0,0,0,0,0.0,0,0,1,0
14,20201,187451,2177-05-25_16:25:00,2106-05-21_13:00:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
15,48233,171452,2198-06-01_07:15:00,2160-12-11_07:11:00,Government,ENGL,PROTESTANT_QUAKER,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
16,95118,192883,2166-04-09_18:59:00,2193-05-06_16:10:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
17,13288,150512,2172-06-25_07:15:00,2163-10-08_16:00:00,Medicare,ENGL,CATHOLIC,SINGLE,BLACK/AFRICAN_AMERICAN,F,...,0,0,0,0,0,0.0,0,0,1,0
18,88252,105206,2186-01-29_18:30:00,2146-06-16_14:37:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
19,53215,128693,2103-12-28_02:14:00,2130-11-04_19:46:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
20,7547,107732,2140-01-13_21:25:00,2100-12-25_14:48:00,Private,ENGL,JEWISH,MARRIED,BLACK/HAITIAN,F,...,0,0,0,0,0,0.0,0,0,0,0
21,87918,191735,2191-07-01_22:13:00,2121-10-10_17:28:00,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
22,70164,157197,2133-10-06_05:14:00,2121-07-05_14:15:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
23,72364,188862,2161-07-29_20:05:00,2120-01-04_14:35:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
24,57773,188304,2151-05-27_18:47:00,2189-09-10_15:45:00,Private,ENGL,PROTESTANT_QUAKER,SINGLE,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
25,76017,183679,2155-01-30_00:05:00,2146-12-29_19:03:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
26,10475,140660,2162-05-30_13:07:00,2169-09-22_12:45:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,1,0
27,40519,142868,2121-02-20_01:05:00,2179-11-17_13:25:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
28,19473,113081,2133-04-28_07:15:00,2151-07-14_19:35:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
29,12791,145253,2127-12-16_07:15:00,2188-05-11_15:55:00,Medicaid,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79969,26668,193566,2181-04-27_23:34:00,2178-08-07_13:58:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
79970,46315,141848,2147-02-10_17:39:00,2150-11-19_11:45:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79971,12510,190855,2131-12-04_19:48:00,2197-05-30_16:45:00,Medicaid,ENGL,OTHER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79972,16322,169887,2172-12-08_07:15:00,2192-01-07_16:30:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79973,30236,110651,2176-09-26_02:09:00,2108-04-06_11:50:00,Private,ENGL,JEWISH,MARRIED,HISPANIC_OR_LATINO,F,...,0,0,0,0,0,0.0,1,0,0,1
79974,10012,187978,2180-05-16_19:40:00,2176-12-19_19:30:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79975,88728,127716,2155-04-20_21:28:00,2167-06-23_19:30:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79976,79348,107589,2151-05-04_21:00:00,2131-09-04_13:00:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79977,6873,135107,2143-12-24_05:28:00,2176-11-26_13:35:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,1,0
79978,17630,109400,2143-03-11_07:55:00,2136-03-20_18:30:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79979,86648,115071,2143-08-23_14:40:00,2201-03-12_15:30:00,Medicare,ENGL,PROTESTANT_QUAKER,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79980,28018,105487,2167-12-18_07:15:00,2138-06-04_20:02:00,Medicare,ENGL,JEWISH,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,1,0,1,1
79981,31039,138637,2196-04-20_19:27:00,2132-02-06_16:25:00,Private,ENGL,PROTESTANT_QUAKER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79982,67619,182950,2162-03-22_13:00:00,2139-08-07_14:55:00,Medicare,ENGL,JEWISH,SINGLE,ASIAN_-_CHINESE,M,...,0,0,0,0,0,0.0,0,0,1,0
79983,72113,127201,2111-06-09_22:57:00,2102-09-28_11:19:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79984,72849,153408,2116-07-06_18:59:00,2141-02-06_15:49:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79985,86108,159149,2124-09-15_15:55:00,2171-04-21_12:24:00,Private,ENGL,JEWISH,SINGLE,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
79986,11603,139934,2132-10-14_23:11:00,2125-11-15_14:38:00,Medicare,ENGL,CATHOLIC,DIVORCED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79987,25105,162373,2136-06-12_19:34:00,2198-09-25_18:20:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79988,74215,124569,2167-03-30_07:15:00,2143-09-04_13:01:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79989,60175,174292,2143-12-04_21:36:00,2152-05-27_13:00:00,Government,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79990,49261,192410,2162-09-24_07:15:00,2113-08-05_17:10:00,Government,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79991,28108,136094,2122-11-25_17:58:00,2144-03-21_16:30:00,Medicare,ENGL,JEWISH,WIDOWED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
79992,28791,168587,2149-05-30_10:45:00,2148-08-31_14:46:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,1
79993,98639,191596,2197-01-13_19:43:00,2203-10-27_15:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79994,63788,148874,2196-08-05_16:06:00,2135-02-10_14:15:00,Medicare,ENGL,NOT_SPECIFIED,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79995,22326,119010,2167-10-06_18:35:00,2121-01-01_16:04:00,Medicaid,ENGL,JEWISH,MARRIED,WHITE,F,...,0,0,0,0,0,1.0,0,0,0,0
79996,81274,183388,2143-04-04_10:30:00,2141-08-09_13:30:00,Private,ENGL,NOT_SPECIFIED,SEPARATED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79997,16587,151289,2183-12-03_02:50:00,2101-08-05_16:00:00,Government,ENGL,CATHOLIC,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79998,17643,145064,2184-05-27_23:46:00,2128-08-04_17:20:00,Government,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0

In [10]:
data.columns = name_col

In [11]:
data

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,...,Eyeinfectn,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn
0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0,0.0,0,0,0,0
3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0,0.0,0,0,0,0
5,11634,144424,2147-08-30_19:51:00,2136-11-19_18:53:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
6,9259,189252,2144-04-26_22:49:00,2199-06-24_10:49:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
7,43732,128084,2194-04-12_01:19:00,2118-09-30_19:00:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,0
8,17978,167487,2159-10-13_23:08:00,2179-09-14_15:40:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,1
9,25610,151971,2119-08-01_07:15:00,2141-09-26_13:15:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
10,1999,144515,2171-09-11_15:27:00,2153-02-20_18:00:00,Medicare,SPAN,PROTESTANT_QUAKER,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,1
11,20651,177259,2145-02-17_17:20:00,2107-09-16_04:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
12,25707,123780,2110-09-17_22:22:00,2198-09-18_16:14:00,Medicare,ENGL,PROTESTANT_QUAKER,DIVORCED,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
13,29887,171410,2192-10-13_18:24:00,2193-05-24_15:25:00,Self_Pay,SPAN,PROTESTANT_QUAKER,SINGLE,HISPANIC/LATINO_-_GUATEMALAN,F,...,0,0,0,0,0,0.0,0,0,1,0
14,20201,187451,2177-05-25_16:25:00,2106-05-21_13:00:00,Medicare,ENGL,CATHOLIC,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
15,48233,171452,2198-06-01_07:15:00,2160-12-11_07:11:00,Government,ENGL,PROTESTANT_QUAKER,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
16,95118,192883,2166-04-09_18:59:00,2193-05-06_16:10:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,1.0,0,0,1,0
17,13288,150512,2172-06-25_07:15:00,2163-10-08_16:00:00,Medicare,ENGL,CATHOLIC,SINGLE,BLACK/AFRICAN_AMERICAN,F,...,0,0,0,0,0,0.0,0,0,1,0
18,88252,105206,2186-01-29_18:30:00,2146-06-16_14:37:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
19,53215,128693,2103-12-28_02:14:00,2130-11-04_19:46:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
20,7547,107732,2140-01-13_21:25:00,2100-12-25_14:48:00,Private,ENGL,JEWISH,MARRIED,BLACK/HAITIAN,F,...,0,0,0,0,0,0.0,0,0,0,0
21,87918,191735,2191-07-01_22:13:00,2121-10-10_17:28:00,Medicare,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
22,70164,157197,2133-10-06_05:14:00,2121-07-05_14:15:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
23,72364,188862,2161-07-29_20:05:00,2120-01-04_14:35:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
24,57773,188304,2151-05-27_18:47:00,2189-09-10_15:45:00,Private,ENGL,PROTESTANT_QUAKER,SINGLE,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
25,76017,183679,2155-01-30_00:05:00,2146-12-29_19:03:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
26,10475,140660,2162-05-30_13:07:00,2169-09-22_12:45:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,1,0
27,40519,142868,2121-02-20_01:05:00,2179-11-17_13:25:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
28,19473,113081,2133-04-28_07:15:00,2151-07-14_19:35:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
29,12791,145253,2127-12-16_07:15:00,2188-05-11_15:55:00,Medicaid,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79969,26668,193566,2181-04-27_23:34:00,2178-08-07_13:58:00,Medicare,ENGL,JEWISH,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,1,0,0,0
79970,46315,141848,2147-02-10_17:39:00,2150-11-19_11:45:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79971,12510,190855,2131-12-04_19:48:00,2197-05-30_16:45:00,Medicaid,ENGL,OTHER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79972,16322,169887,2172-12-08_07:15:00,2192-01-07_16:30:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79973,30236,110651,2176-09-26_02:09:00,2108-04-06_11:50:00,Private,ENGL,JEWISH,MARRIED,HISPANIC_OR_LATINO,F,...,0,0,0,0,0,0.0,1,0,0,1
79974,10012,187978,2180-05-16_19:40:00,2176-12-19_19:30:00,Medicare,ENGL,CATHOLIC,WIDOWED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79975,88728,127716,2155-04-20_21:28:00,2167-06-23_19:30:00,Private,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79976,79348,107589,2151-05-04_21:00:00,2131-09-04_13:00:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79977,6873,135107,2143-12-24_05:28:00,2176-11-26_13:35:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,1,0
79978,17630,109400,2143-03-11_07:55:00,2136-03-20_18:30:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79979,86648,115071,2143-08-23_14:40:00,2201-03-12_15:30:00,Medicare,ENGL,PROTESTANT_QUAKER,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79980,28018,105487,2167-12-18_07:15:00,2138-06-04_20:02:00,Medicare,ENGL,JEWISH,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,1,0,1,1
79981,31039,138637,2196-04-20_19:27:00,2132-02-06_16:25:00,Private,ENGL,PROTESTANT_QUAKER,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79982,67619,182950,2162-03-22_13:00:00,2139-08-07_14:55:00,Medicare,ENGL,JEWISH,SINGLE,ASIAN_-_CHINESE,M,...,0,0,0,0,0,0.0,0,0,1,0
79983,72113,127201,2111-06-09_22:57:00,2102-09-28_11:19:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79984,72849,153408,2116-07-06_18:59:00,2141-02-06_15:49:00,Medicare,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,1,0
79985,86108,159149,2124-09-15_15:55:00,2171-04-21_12:24:00,Private,ENGL,JEWISH,SINGLE,UNKNOWN/NOT_SPECIFIED,M,...,0,0,0,0,0,0.0,0,0,1,0
79986,11603,139934,2132-10-14_23:11:00,2125-11-15_14:38:00,Medicare,ENGL,CATHOLIC,DIVORCED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79987,25105,162373,2136-06-12_19:34:00,2198-09-25_18:20:00,Private,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79988,74215,124569,2167-03-30_07:15:00,2143-09-04_13:01:00,Medicare,ENGL,OTHER,SINGLE,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79989,60175,174292,2143-12-04_21:36:00,2152-05-27_13:00:00,Government,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79990,49261,192410,2162-09-24_07:15:00,2113-08-05_17:10:00,Government,ENGL,UNOBTAINABLE,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79991,28108,136094,2122-11-25_17:58:00,2144-03-21_16:30:00,Medicare,ENGL,JEWISH,WIDOWED,WHITE,M,...,0,0,0,0,0,1.0,0,0,0,0
79992,28791,168587,2149-05-30_10:45:00,2148-08-31_14:46:00,Private,ENGL,NOT_SPECIFIED,MARRIED,WHITE,F,...,0,0,0,0,0,0.0,1,0,0,1
79993,98639,191596,2197-01-13_19:43:00,2203-10-27_15:00:00,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0
79994,63788,148874,2196-08-05_16:06:00,2135-02-10_14:15:00,Medicare,ENGL,NOT_SPECIFIED,UNKNOWN_(DEFAULT),WHITE,F,...,0,0,0,0,0,0.0,0,0,1,0
79995,22326,119010,2167-10-06_18:35:00,2121-01-01_16:04:00,Medicaid,ENGL,JEWISH,MARRIED,WHITE,F,...,0,0,0,0,0,1.0,0,0,0,0
79996,81274,183388,2143-04-04_10:30:00,2141-08-09_13:30:00,Private,ENGL,NOT_SPECIFIED,SEPARATED,WHITE,F,...,0,0,0,0,0,0.0,0,0,0,0
79997,16587,151289,2183-12-03_02:50:00,2101-08-05_16:00:00,Government,ENGL,CATHOLIC,MARRIED,BLACK/AFRICAN_AMERICAN,M,...,0,0,0,0,0,0.0,0,0,1,0
79998,17643,145064,2184-05-27_23:46:00,2128-08-04_17:20:00,Government,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0,0.0,0,0,0,0

In [12]:
died = pd.read_table('mimic_synthetic_train.solution',sep='\n',header=None)

C:\Users\B.K Goel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [13]:
died.head()

   0
0  0
1  0
2  0
3  0
4  0

In [14]:
died.columns = ['DIED']

In [15]:
died.head()

   DIED
0     0
1     0
2     0
3     0
4     0

In [16]:
data = pd.concat([data,died],axis=1)

In [17]:
data.head()

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
0,45524,108398,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0.0,0,0,0,0,0
1,50520,186416,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0.0,0,0,0,1,0
2,17956,126413,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0.0,0,0,0,0,0
3,90258,109355,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0.0,0,0,1,0,0
4,25159,123784,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0.0,0,0,0,0,0

In [18]:
num_cols = []
categorical_col = []

for cols in data.columns:
    if data[cols].dtype == object:
        categorical_col.append(cols)
    else:
        num_cols.append(cols)

In [19]:
print('length of numerical columns',len(num_cols))
print('length of categorical columns',len(categorical_col))

length of numerical columns 333
length of categorical columns 9

In [20]:
data.describe()

,SUBJECT_ID,HADM_ID,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,SYS_BP_MEAN_DAY1,DIAS_BP_MIN_DAY1,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
count,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,...,79999.000000,79999.0,79999.0,79999.0,79998.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000
mean,37927.384230,150061.011025,62.660546,71.648531,103.083037,86.394036,94.612069,147.790712,119.655538,45.243690,...,0.000013,0.0,0.0,0.0,0.145454,0.134177,0.008625,0.457693,0.078976,0.034963
std,29300.394392,29005.267607,18.193723,14.652553,18.479082,15.510917,16.940341,21.609206,16.486749,10.499518,...,0.003536,0.0,0.0,0.0,0.352560,0.340844,0.092471,0.498210,0.269703,0.183687
min,3.000000,100001.000000,16.000000,18.728695,49.860610,38.503600,31.768501,91.693405,73.968796,11.334383,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,13853.000000,124750.000000,51.000000,61.458639,89.897490,75.284898,82.811535,132.121700,107.559967,37.831446,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27591.000000,150045.000000,65.000000,71.049320,101.585940,85.421690,94.168460,145.412140,118.117890,44.621235,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,62471.000000,175452.000000,77.000000,81.148908,114.800830,96.505275,105.964120,161.115990,130.294615,51.966651,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,99999.000000,199999.000000,90.000000,141.859680,206.621150,157.612470,163.822920,260.044980,186.328400,95.604270,...,1.000000,0.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [21]:
data[categorical_col].head()

,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,ICU
0,2128-05-15_23:42:00,2132-07-23_15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,SICU
1,2134-03-17_03:59:00,2113-03-06_12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,CCU
2,2164-04-05_17:32:00,2180-09-20_16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,MICU
3,2102-09-08_00:58:00,2166-06-26_15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,CCU
4,2163-08-06_12:07:00,2147-01-14_18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,MICU

In [22]:
data['MARITAL_STATUS'].value_counts()

MARRIED              43661
SINGLE               18318
WIDOWED               9375
DIVORCED              5015
UNKNOWN_(DEFAULT)     2114
SEPARATED             1139
LIFE_PARTNER           376
Name: MARITAL_STATUS, dtype: int64

In [23]:
data['INSURANCE'].value_counts()

Medicare      44670
Private       23964
Medicaid       6434
Government     2933
Self_Pay       1998
Name: INSURANCE, dtype: int64

In [24]:
data.get_dtype_counts()

float64     51
int64      282
object       9
dtype: int64

In [25]:
data['ADMITTIME'] = data['ADMITTIME'].str.replace('_',' ')

In [26]:
data['ADMITTIME'] = pd.to_datetime(data['ADMITTIME'])

In [27]:
data['ADMITTIME'].dtype

dtype('<M8[ns]')

In [28]:
data['DISCHTIME'] = data['DISCHTIME'].str.replace('_',' ')

In [29]:
data['DISCHTIME'] = pd.to_datetime(data['DISCHTIME'])

In [30]:
data['DISCHTIME'].dtype

dtype('<M8[ns]')

In [31]:
data.head()

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,GENDER,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
0,45524,108398,2128-05-15 23:42:00,2132-07-23 15:00:00,Private,ENGL,CATHOLIC,DIVORCED,WHITE,F,...,0,0,0,0,0.0,0,0,0,0,0
1,50520,186416,2134-03-17 03:59:00,2113-03-06 12:05:00,Private,ENGL,UNOBTAINABLE,SINGLE,WHITE,M,...,0,0,0,0,0.0,0,0,0,1,0
2,17956,126413,2164-04-05 17:32:00,2180-09-20 16:30:00,Medicaid,SPAN,CATHOLIC,WIDOWED,OTHER,M,...,0,0,0,0,0.0,0,0,0,0,0
3,90258,109355,2102-09-08 00:58:00,2166-06-26 15:30:00,Medicare,ENGL,NOT_SPECIFIED,MARRIED,WHITE,M,...,0,0,0,0,0.0,0,0,1,0,0
4,25159,123784,2163-08-06 12:07:00,2147-01-14 18:40:00,Medicare,ENGL,UNOBTAINABLE,MARRIED,UNKNOWN/NOT_SPECIFIED,F,...,0,0,0,0,0.0,0,0,0,0,0

In [32]:
data['ETHNICITY'].value_counts()

WHITE                                                       59728
UNKNOWN/NOT_SPECIFIED                                        4343
BLACK/AFRICAN_AMERICAN                                       3718
OTHER                                                        1647
HISPANIC_OR_LATINO                                           1429
ASIAN                                                        1416
UNABLE_TO_OBTAIN                                             1384
PATIENT_DECLINED_TO_ANSWER                                   1085
ASIAN_-_CHINESE                                               541
HISPANIC/LATINO_-_PUERTO_RICAN                                466
BLACK/CAPE_VERDEAN                                            426
WHITE_-_RUSSIAN                                               393
MULTI_RACE_ETHNICITY                                          357
HISPANIC/LATINO_-_DOMINICAN                                   290
BLACK/HAITIAN                                                 267
WHITE_-_OTHER_EUROPEAN                                        266
ASIAN_-_ASIAN_INDIAN                                          246
PORTUGUESE                                                    213
WHITE_-_BRAZILIAN                                             205
ASIAN_-_VIETNAMESE                                            189
BLACK/AFRICAN                                                 176
HISPANIC/LATINO_-_GUATEMALAN                                  136
AMERICAN_INDIAN/ALASKA_NATIVE                                 132
MIDDLE_EASTERN                                                120
WHITE_-_EASTERN_EUROPEAN                                      101
ASIAN_-_OTHER                                                  89
HISPANIC/LATINO_-_CUBAN                                        83
ASIAN_-_FILIPINO                                               65
HISPANIC/LATINO_-_CENTRAL_AMERICAN_(OTHER)                     62
ASIAN_-_CAMBODIAN                                              60
NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER                      60
ASIAN_-_KOREAN                                                 60
HISPANIC/LATINO_-_MEXICAN                                      49
HISPANIC/LATINO_-_COLOMBIAN                                    46
SOUTH_AMERICAN                                                 46
CARIBBEAN_ISLAND                                               37
ASIAN_-_JAPANESE                                               31
HISPANIC/LATINO_-_SALVADORAN                                   20
ASIAN_-_THAI                                                   10
HISPANIC/LATINO_-_HONDURAN                                      6
AMERICAN_INDIAN/ALASKA_NATIVE_FEDERALLY_RECOGNIZED_TRIBE        1
Name: ETHNICITY, dtype: int64

In [33]:
data[num_cols].describe()

,SUBJECT_ID,HADM_ID,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,SYS_BP_MEAN_DAY1,DIAS_BP_MIN_DAY1,...,Othereyedx,Otitismedia,Dizziness,Othereardx,Othnervdx,Hrtvalvedx,Carditis,HTN,Htncomplicn,DIED
count,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000,...,79999.000000,79999.0,79999.0,79999.0,79998.000000,79999.000000,79999.000000,79999.000000,79999.000000,79999.000000
mean,37927.384230,150061.011025,62.660546,71.648531,103.083037,86.394036,94.612069,147.790712,119.655538,45.243690,...,0.000013,0.0,0.0,0.0,0.145454,0.134177,0.008625,0.457693,0.078976,0.034963
std,29300.394392,29005.267607,18.193723,14.652553,18.479082,15.510917,16.940341,21.609206,16.486749,10.499518,...,0.003536,0.0,0.0,0.0,0.352560,0.340844,0.092471,0.498210,0.269703,0.183687
min,3.000000,100001.000000,16.000000,18.728695,49.860610,38.503600,31.768501,91.693405,73.968796,11.334383,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,13853.000000,124750.000000,51.000000,61.458639,89.897490,75.284898,82.811535,132.121700,107.559967,37.831446,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27591.000000,150045.000000,65.000000,71.049320,101.585940,85.421690,94.168460,145.412140,118.117890,44.621235,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,62471.000000,175452.000000,77.000000,81.148908,114.800830,96.505275,105.964120,161.115990,130.294615,51.966651,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,99999.000000,199999.000000,90.000000,141.859680,206.621150,157.612470,163.822920,260.044980,186.328400,95.604270,...,1.000000,0.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [34]:
from sklearn.impute import SimpleImputer

In [35]:
imputer = SimpleImputer(strategy='median')

In [36]:
data[num_cols] = imputer.fit_transform(data[num_cols])

In [37]:
data = pd.get_dummies(data)

In [38]:
data.head()

,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,...,ETHNICITY_WHITE_-_EASTERN_EUROPEAN,ETHNICITY_WHITE_-_OTHER_EUROPEAN,ETHNICITY_WHITE_-_RUSSIAN,GENDER_F,GENDER_M,ICU_CCU,ICU_CSRU,ICU_MICU,ICU_SICU,ICU_TSICU
0,45524.0,108398.0,2128-05-15 23:42:00,2132-07-23 15:00:00,21.0,57.207630,108.704030,70.841980,79.847060,119.72417,...,0,0,0,1,0,0,0,0,1,0
1,50520.0,186416.0,2134-03-17 03:59:00,2113-03-06 12:05:00,39.0,79.331400,121.138664,96.915726,93.994540,138.59406,...,0,0,0,0,1,1,0,0,0,0
2,17956.0,126413.0,2164-04-05 17:32:00,2180-09-20 16:30:00,40.0,118.230290,175.175430,140.936700,122.862610,144.25964,...,0,0,0,0,1,0,0,1,0,0
3,90258.0,109355.0,2102-09-08 00:58:00,2166-06-26 15:30:00,75.0,83.780380,89.188980,86.051155,111.390740,144.86057,...,0,0,0,0,1,1,0,0,0,0
4,25159.0,123784.0,2163-08-06 12:07:00,2147-01-14 18:40:00,55.0,60.878613,105.637500,80.616840,87.627464,127.75874,...,0,0,0,1,0,0,0,1,0,0

In [39]:
temp = pd.CategoricalDtype(data)

In [40]:
data.to_csv("Dummy.csv")

In [41]:
data.drop(['ADMITTIME','HADM_ID'], axis=1, inplace=True)

In [50]:
data

,DISCHTIME,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,SYS_BP_MEAN_DAY1,DIAS_BP_MIN_DAY1,DIAS_BP_MAX_DAY1,...,ETHNICITY_WHITE_-_EASTERN_EUROPEAN,ETHNICITY_WHITE_-_OTHER_EUROPEAN,ETHNICITY_WHITE_-_RUSSIAN,GENDER_F,GENDER_M,ICU_CCU,ICU_CSRU,ICU_MICU,ICU_SICU,ICU_TSICU
0,2132-07-23 15:00:00,21.0,57.207630,108.704030,70.841980,79.847060,119.724170,94.435090,26.880910,68.876540,...,0,0,0,1,0,0,0,0,1,0
1,2113-03-06 12:05:00,39.0,79.331400,121.138664,96.915726,93.994540,138.594060,113.570206,38.621536,74.270065,...,0,0,0,0,1,1,0,0,0,0
2,2180-09-20 16:30:00,40.0,118.230290,175.175430,140.936700,122.862610,144.259640,134.501220,67.754650,83.301410,...,0,0,0,0,1,0,0,1,0,0
3,2166-06-26 15:30:00,75.0,83.780380,89.188980,86.051155,111.390740,144.860570,127.681170,61.139935,75.232390,...,0,0,0,0,1,1,0,0,0,0
4,2147-01-14 18:40:00,55.0,60.878613,105.637500,80.616840,87.627464,127.758740,99.098860,42.693020,64.015396,...,0,0,0,1,0,0,0,1,0,0
5,2136-11-19 18:53:00,66.0,40.019630,68.435030,60.395480,97.198326,140.940100,109.457480,43.979748,79.828740,...,0,0,0,1,0,0,0,0,0,1
6,2199-06-24 10:49:00,88.0,56.889404,98.787170,70.732290,86.096176,159.573210,131.438400,56.737286,98.919030,...,0,0,0,0,1,0,0,0,0,1
7,2118-09-30 19:00:00,81.0,62.002815,85.822970,84.520810,99.672120,154.289980,125.882450,28.898981,59.936455,...,0,0,0,1,0,0,1,0,0,0
8,2179-09-14 15:40:00,57.0,89.705830,110.043200,113.968720,115.572910,189.999910,144.896330,44.581734,91.606636,...,0,0,0,0,1,0,1,0,0,0
9,2141-09-26 13:15:00,90.0,73.032040,102.122310,94.104660,82.418770,121.329730,93.741880,34.476383,55.915947,...,0,0,0,0,1,1,0,0,0,0
10,2153-02-20 18:00:00,63.0,41.319670,71.347460,52.442623,90.963580,146.204300,110.412430,41.630325,84.953260,...,0,0,0,0,1,0,1,0,0,0
11,2107-09-16 04:00:00,64.0,101.644070,134.407800,110.352844,79.336730,110.432080,105.360504,36.882175,65.265790,...,0,0,0,0,1,0,0,1,0,0
12,2198-09-18 16:14:00,55.0,73.463950,88.438340,76.268070,76.257270,139.031650,106.293230,40.091670,86.661090,...,0,0,0,0,1,0,0,0,1,0
13,2193-05-24 15:25:00,76.0,78.248230,139.058100,110.512910,105.705666,164.979400,125.368400,52.027176,105.721530,...,0,0,0,1,0,0,0,0,1,0
14,2106-05-21 13:00:00,36.0,66.881220,96.671400,81.779710,90.839030,126.981950,115.341900,38.813335,65.540600,...,0,0,0,0,1,0,0,1,0,0
15,2160-12-11 07:11:00,37.0,80.773420,103.540230,107.007770,98.777180,141.293950,127.072200,57.954468,82.938095,...,0,0,0,1,0,0,1,0,0,0
16,2193-05-06 16:10:00,64.0,79.414870,119.652850,99.952910,119.728660,172.254460,138.375210,51.860070,122.840410,...,0,0,0,0,1,0,1,0,0,0
17,2163-10-08 16:00:00,60.0,51.682550,85.629745,67.373570,99.447495,118.184370,120.174484,32.505920,72.026700,...,0,0,0,1,0,0,0,0,0,1
18,2146-06-16 14:37:00,90.0,60.492740,104.187450,77.941590,79.155876,186.006500,137.332900,36.059082,79.699940,...,0,0,0,0,1,0,0,0,1,0
19,2130-11-04 19:46:00,81.0,59.078120,70.426200,61.185905,82.630630,113.507570,95.399980,43.682000,53.666530,...,0,0,0,0,1,0,0,0,1,0
20,2100-12-25 14:48:00,34.0,98.991170,120.642395,93.795690,51.198875,113.630020,95.707954,33.320465,61.209167,...,0,0,0,1,0,0,0,0,1,0
21,2121-10-10 17:28:00,55.0,79.767610,111.566345,85.938710,107.014305,170.289660,145.792020,43.720276,68.288230,...,0,0,0,1,0,0,0,0,0,1
22,2121-07-05 14:15:00,69.0,77.108050,93.200710,86.516770,79.500160,132.892320,108.033676,35.091003,69.385420,...,0,0,0,1,0,1,0,0,0,0
23,2120-01-04 14:35:00,85.0,64.903530,96.580890,77.680220,97.276436,139.850890,127.166855,47.621178,99.293000,...,0,0,0,0,1,0,0,0,0,1
24,2189-09-10 15:45:00,44.0,69.077484,96.672290,91.116460,94.860820,150.901890,113.191820,45.150020,132.367030,...,0,0,0,1,0,0,0,1,0,0
25,2146-12-29 19:03:00,28.0,87.642296,134.623030,106.568710,80.030840,124.121090,107.020830,44.417637,72.552795,...,0,0,0,0,1,1,0,0,0,0
26,2169-09-22 12:45:00,84.0,78.439354,113.411960,87.992460,84.781624,152.454990,99.413700,56.902267,83.120210,...,0,0,0,0,1,0,0,0,0,1
27,2179-11-17 13:25:00,57.0,78.071754,112.386720,99.531740,68.227806,117.930340,88.682205,29.009010,73.337320,...,0,0,0,0,1,0,0,1,0,0
28,2151-07-14 19:35:00,64.0,72.914360,82.820850,84.893166,104.362170,166.758090,122.318085,47.606150,64.586685,...,0,0,0,0,1,0,0,0,0,1
29,2188-05-11 15:55:00,52.0,103.408170,167.173320,115.460280,66.977745,134.228090,106.490310,33.480194,81.642200,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79969,2178-08-07 13:58:00,77.0,65.004974,81.170380,63.805458,101.735855,138.423110,117.324110,47.621845,69.419260,...,0,0,0,0,1,0,1,0,0,0
79970,2150-11-19 11:45:00,79.0,76.098680,132.967160,96.169620,78.420480,118.965760,91.773834,28.709198,60.598156,...,0,0,0,1,0,0,0,1,0,0
79971,2197-05-30 16:45:00,54.0,69.226110,99.408104,81.294020,123.959430,170.778380,142.631130,58.420727,113.153020,...,0,0,0,1,0,0,0,1,0,0
79972,2192-01-07 16:30:00,39.0,82.600494,92.711740,94.884420,93.400894,123.672650,102.151750,54.732876,70.854860,...,0,0,0,1,0,0,1,0,0,0
79973,2108-04-06 11:50:00,88.0,62.056600,94.649020,81.849000,79.345160,127.790450,94.974960,36.040370,60.723076,...,0,0,0,1,0,0,0,1,0,0
79974,2176-12-19 19:30:00,82.0,85.768680,139.812160,108.483990,87.464450,178.861150,133.074020,53.353775,138.093020,...,0,0,0,1,0,0,0,1,0,0
79975,2167-06-23 19:30:00,38.0,61.552055,90.395690,82.902510,59.205480,115.060715,92.045100,37.720028,62.568880,...,0,0,0,1,0,0,0,1,0,0
79976,2131-09-04 13:00:00,87.0,70.973850,99.535540,89.205040,118.066310,108.818340,105.999040,60.905174,66.072770,...,0,0,0,0,1,0,0,0,1,0
79977,2176-11-26 13:35:00,83.0,53.898520,75.743744,74.494430,118.117230,142.445850,135.433850,54.425987,85.683450,...,0,0,0,1,0,0,1,0,0,0
79978,2136-03-20 18:30:00,66.0,100.181656,147.515580,119.098560,94.339420,165.260220,124.551090,49.449615,100.067190,...,0,0,0,1,0,0,0,1,0,0
79979,2201-03-12 15:30:00,71.0,57.584260,83.788086,70.115950,90.495350,155.379430,125.575940,53.610153,103.024600,...,0,0,0,0,1,1,0,0,0,0
79980,2138-06-04 20:02:00,90.0,72.604034,118.367460,90.445160,105.093790,170.613530,122.055725,39.259274,88.049240,...,0,0,0,1,0,0,0,1,0,0
79981,2132-02-06 16:25:00,50.0,49.830906,83.378240,58.176370,93.972710,150.715070,126.203780,65.547104,73.743070,...,0,0,0,1,0,0,0,0,0,1
79982,2139-08-07 14:55:00,70.0,103.120940,110.124670,104.945270,85.572970,134.944430,113.874405,47.145370,80.669980,...,0,0,0,0,1,0,0,1,0,0
79983,2102-09-28 11:19:00,82.0,80.327170,108.398610,83.052826,89.477350,148.004600,107.927600,28.264824,73.045334,...,0,0,0,0,1,0,1,0,0,0
79984,2141-02-06 15:49:00,31.0,82.391140,105.209450,92.576890,114.534590,171.781680,146.631740,52.878754,93.323030,...,0,0,0,0,1,0,0,0,0,1
79985,2171-04-21 12:24:00,40.0,67.079910,112.304290,83.068010,127.167230,129.935910,131.869740,64.635130,107.014700,...,0,0,0,0,1,1,0,0,0,0
79986,2125-11-15 14:38:00,65.0,75.014885,122.197240,97.442600,98.030365,150.284320,122.432160,50.067455,77.230790,...,0,0,0,0,1,0,0,0,1,0
79987,2198-09-25 18:20:00,46.0,60.215885,113.693260,88.344420,84.842710,131.043820,109.881040,54.328835,100.503690,...,0,0,0,0,1,1,0,0,0,0
79988,2143-09-04 13:01:00,80.0,60.669067,99.986640,88.701370,109.735220,156.366700,121.617966,40.035954,82.014694,...,0,0,0,0,1,0,0,1,0,0
79989,2152-05-27 13:00:00,26.0,52.419620,71.537430,61.549423,93.818436,127.343810,103.136536,30.538132,79.529200,...,0,0,0,0,1,0,0,1,0,0
79990,2113-08-05 17:10:00,44.0,95.255210,120.259190,105.865400,109.160576,149.261440,129.275100,57.886460,100.431625,...,0,0,0,1,0,0,0,0,1,0
79991,2144-03-21 16:30:00,58.0,52.078370,95.686160,68.507070,74.252950,129.944500,98.534590,32.176910,69.578110,...,0,0,0,0,1,0,1,0,0,0
79992,2148-08-31 14:46:00,42.0,54.910847,88.564760,68.762634,123.024220,163.616440,118.623670,43.968536,87.845450,...,0,0,0,1,0,0,1,0,0,0
79993,2203-10-27 15:00:00,67.0,65.964294,98.301140,79.597786,98.248380,161.336730,135.709900,37.492912,90.884155,...,0,0,0,0,1,0,1,0,0,0
79994,2135-02-10 14:15:00,76.0,56.035793,97.863950,79.709885,77.546234,120.307580,102.489240,26.716347,49.722248,...,0,0,0,1,0,0,1,0,0,0
79995,2121-01-01 16:04:00,38.0,55.126850,86.027390,67.647910,83.051470,174.834460,119.396470,40.401726,79.416885,...,0,0,0,1,0,0,0,0,0,1
79996,2141-08-09 13:30:00,90.0,74.281746,91.267840,91.425380,95.857544,138.798030,130.716320,52.676624,85.140060,...,0,0,0,1,0,0,0,0,1,0
79997,2101-08-05 16:00:00,57.0,79.256140,128.995130,98.742550,107.726430,141.928340,132.398940,57.103550,77.403870,...,0,0,0,0,1,0,0,0,0,1
79998,2128-08-04 17:20:00,37.0,84.979800,133.152620,94.290375,82.892820,141.696470,107.498764,48.055770,97.403990,...,0,0,0,0,1,0,1,0,0,0

In [51]:
data.drop('DISCHTIME', axis=1, inplace=True)
data

,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,SYS_BP_MEAN_DAY1,DIAS_BP_MIN_DAY1,DIAS_BP_MAX_DAY1,DIAS_BP_MEAN_DAY1,...,ETHNICITY_WHITE_-_EASTERN_EUROPEAN,ETHNICITY_WHITE_-_OTHER_EUROPEAN,ETHNICITY_WHITE_-_RUSSIAN,GENDER_F,GENDER_M,ICU_CCU,ICU_CSRU,ICU_MICU,ICU_SICU,ICU_TSICU
0,21.0,57.207630,108.704030,70.841980,79.847060,119.724170,94.435090,26.880910,68.876540,48.665768,...,0,0,0,1,0,0,0,0,1,0
1,39.0,79.331400,121.138664,96.915726,93.994540,138.594060,113.570206,38.621536,74.270065,66.566760,...,0,0,0,0,1,1,0,0,0,0
2,40.0,118.230290,175.175430,140.936700,122.862610,144.259640,134.501220,67.754650,83.301410,80.350330,...,0,0,0,0,1,0,0,1,0,0
3,75.0,83.780380,89.188980,86.051155,111.390740,144.860570,127.681170,61.139935,75.232390,74.849920,...,0,0,0,0,1,1,0,0,0,0
4,55.0,60.878613,105.637500,80.616840,87.627464,127.758740,99.098860,42.693020,64.015396,64.309480,...,0,0,0,1,0,0,0,1,0,0
5,66.0,40.019630,68.435030,60.395480,97.198326,140.940100,109.457480,43.979748,79.828740,63.191380,...,0,0,0,1,0,0,0,0,0,1
6,88.0,56.889404,98.787170,70.732290,86.096176,159.573210,131.438400,56.737286,98.919030,74.194885,...,0,0,0,0,1,0,0,0,0,1
7,81.0,62.002815,85.822970,84.520810,99.672120,154.289980,125.882450,28.898981,59.936455,44.481770,...,0,0,0,1,0,0,1,0,0,0
8,57.0,89.705830,110.043200,113.968720,115.572910,189.999910,144.896330,44.581734,91.606636,67.561600,...,0,0,0,0,1,0,1,0,0,0
9,90.0,73.032040,102.122310,94.104660,82.418770,121.329730,93.741880,34.476383,55.915947,41.967148,...,0,0,0,0,1,1,0,0,0,0
10,63.0,41.319670,71.347460,52.442623,90.963580,146.204300,110.412430,41.630325,84.953260,57.450000,...,0,0,0,0,1,0,1,0,0,0
11,64.0,101.644070,134.407800,110.352844,79.336730,110.432080,105.360504,36.882175,65.265790,53.860320,...,0,0,0,0,1,0,0,1,0,0
12,55.0,73.463950,88.438340,76.268070,76.257270,139.031650,106.293230,40.091670,86.661090,72.196106,...,0,0,0,0,1,0,0,0,1,0
13,76.0,78.248230,139.058100,110.512910,105.705666,164.979400,125.368400,52.027176,105.721530,78.360610,...,0,0,0,1,0,0,0,0,1,0
14,36.0,66.881220,96.671400,81.779710,90.839030,126.981950,115.341900,38.813335,65.540600,53.805280,...,0,0,0,0,1,0,0,1,0,0
15,37.0,80.773420,103.540230,107.007770,98.777180,141.293950,127.072200,57.954468,82.938095,69.202500,...,0,0,0,1,0,0,1,0,0,0
16,64.0,79.414870,119.652850,99.952910,119.728660,172.254460,138.375210,51.860070,122.840410,71.385086,...,0,0,0,0,1,0,1,0,0,0
17,60.0,51.682550,85.629745,67.373570,99.447495,118.184370,120.174484,32.505920,72.026700,46.775060,...,0,0,0,1,0,0,0,0,0,1
18,90.0,60.492740,104.187450,77.941590,79.155876,186.006500,137.332900,36.059082,79.699940,50.416332,...,0,0,0,0,1,0,0,0,1,0
19,81.0,59.078120,70.426200,61.185905,82.630630,113.507570,95.399980,43.682000,53.666530,46.149635,...,0,0,0,0,1,0,0,0,1,0
20,34.0,98.991170,120.642395,93.795690,51.198875,113.630020,95.707954,33.320465,61.209167,54.182594,...,0,0,0,1,0,0,0,0,1,0
21,55.0,79.767610,111.566345,85.938710,107.014305,170.289660,145.792020,43.720276,68.288230,61.820965,...,0,0,0,1,0,0,0,0,0,1
22,69.0,77.108050,93.200710,86.516770,79.500160,132.892320,108.033676,35.091003,69.385420,60.785103,...,0,0,0,1,0,1,0,0,0,0
23,85.0,64.903530,96.580890,77.680220,97.276436,139.850890,127.166855,47.621178,99.293000,59.442684,...,0,0,0,0,1,0,0,0,0,1
24,44.0,69.077484,96.672290,91.116460,94.860820,150.901890,113.191820,45.150020,132.367030,76.405410,...,0,0,0,1,0,0,0,1,0,0
25,28.0,87.642296,134.623030,106.568710,80.030840,124.121090,107.020830,44.417637,72.552795,61.617940,...,0,0,0,0,1,1,0,0,0,0
26,84.0,78.439354,113.411960,87.992460,84.781624,152.454990,99.413700,56.902267,83.120210,72.047134,...,0,0,0,0,1,0,0,0,0,1
27,57.0,78.071754,112.386720,99.531740,68.227806,117.930340,88.682205,29.009010,73.337320,42.056540,...,0,0,0,0,1,0,0,1,0,0
28,64.0,72.914360,82.820850,84.893166,104.362170,166.758090,122.318085,47.606150,64.586685,55.557260,...,0,0,0,0,1,0,0,0,0,1
29,52.0,103.408170,167.173320,115.460280,66.977745,134.228090,106.490310,33.480194,81.642200,53.959340,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79969,77.0,65.004974,81.170380,63.805458,101.735855,138.423110,117.324110,47.621845,69.419260,57.718430,...,0,0,0,0,1,0,1,0,0,0
79970,79.0,76.098680,132.967160,96.169620,78.420480,118.965760,91.773834,28.709198,60.598156,41.826250,...,0,0,0,1,0,0,0,1,0,0
79971,54.0,69.226110,99.408104,81.294020,123.959430,170.778380,142.631130,58.420727,113.153020,77.973206,...,0,0,0,1,0,0,0,1,0,0
79972,39.0,82.600494,92.711740,94.884420,93.400894,123.672650,102.151750,54.732876,70.854860,59.894950,...,0,0,0,1,0,0,1,0,0,0
79973,88.0,62.056600,94.649020,81.849000,79.345160,127.790450,94.974960,36.040370,60.723076,50.672210,...,0,0,0,1,0,0,0,1,0,0
79974,82.0,85.768680,139.812160,108.483990,87.464450,178.861150,133.074020,53.353775,138.093020,91.029380,...,0,0,0,1,0,0,0,1,0,0
79975,38.0,61.552055,90.395690,82.902510,59.205480,115.060715,92.045100,37.720028,62.568880,53.481520,...,0,0,0,1,0,0,0,1,0,0
79976,87.0,70.973850,99.535540,89.205040,118.066310,108.818340,105.999040,60.905174,66.072770,62.635586,...,0,0,0,0,1,0,0,0,1,0
79977,83.0,53.898520,75.743744,74.494430,118.117230,142.445850,135.433850,54.425987,85.683450,65.936590,...,0,0,0,1,0,0,1,0,0,0
79978,66.0,100.181656,147.515580,119.098560,94.339420,165.260220,124.551090,49.449615,100.067190,78.311480,...,0,0,0,1,0,0,0,1,0,0
79979,71.0,57.584260,83.788086,70.115950,90.495350,155.379430,125.575940,53.610153,103.024600,67.884094,...,0,0,0,0,1,1,0,0,0,0
79980,90.0,72.604034,118.367460,90.445160,105.093790,170.613530,122.055725,39.259274,88.049240,57.085243,...,0,0,0,1,0,0,0,1,0,0
79981,50.0,49.830906,83.378240,58.176370,93.972710,150.715070,126.203780,65.547104,73.743070,64.331510,...,0,0,0,1,0,0,0,0,0,1
79982,70.0,103.120940,110.124670,104.945270,85.572970,134.944430,113.874405,47.145370,80.669980,57.979458,...,0,0,0,0,1,0,0,1,0,0
79983,82.0,80.327170,108.398610,83.052826,89.477350,148.004600,107.927600,28.264824,73.045334,49.039840,...,0,0,0,0,1,0,1,0,0,0
79984,31.0,82.391140,105.209450,92.576890,114.534590,171.781680,146.631740,52.878754,93.323030,70.542330,...,0,0,0,0,1,0,0,0,0,1
79985,40.0,67.079910,112.304290,83.068010,127.167230,129.935910,131.869740,64.635130,107.014700,76.436430,...,0,0,0,0,1,1,0,0,0,0
79986,65.0,75.014885,122.197240,97.442600,98.030365,150.284320,122.432160,50.067455,77.230790,66.038830,...,0,0,0,0,1,0,0,0,1,0
79987,46.0,60.215885,113.693260,88.344420,84.842710,131.043820,109.881040,54.328835,100.503690,74.592160,...,0,0,0,0,1,1,0,0,0,0
79988,80.0,60.669067,99.986640,88.701370,109.735220,156.366700,121.617966,40.035954,82.014694,60.272198,...,0,0,0,0,1,0,0,1,0,0
79989,26.0,52.419620,71.537430,61.549423,93.818436,127.343810,103.136536,30.538132,79.529200,48.255760,...,0,0,0,0,1,0,0,1,0,0
79990,44.0,95.255210,120.259190,105.865400,109.160576,149.261440,129.275100,57.886460,100.431625,77.056076,...,0,0,0,1,0,0,0,0,1,0
79991,58.0,52.078370,95.686160,68.507070,74.252950,129.944500,98.534590,32.176910,69.578110,45.490440,...,0,0,0,0,1,0,1,0,0,0
79992,42.0,54.910847,88.564760,68.762634,123.024220,163.616440,118.623670,43.968536,87.845450,61.533707,...,0,0,0,1,0,0,1,0,0,0
79993,67.0,65.964294,98.301140,79.597786,98.248380,161.336730,135.709900,37.492912,90.884155,57.411150,...,0,0,0,0,1,0,1,0,0,0
79994,76.0,56.035793,97.863950,79.709885,77.546234,120.307580,102.489240,26.716347,49.722248,47.403100,...,0,0,0,1,0,0,1,0,0,0
79995,38.0,55.126850,86.027390,67.647910,83.051470,174.834460,119.396470,40.401726,79.416885,55.099426,...,0,0,0,1,0,0,0,0,0,1
79996,90.0,74.281746,91.267840,91.425380,95.857544,138.798030,130.716320,52.676624,85.140060,65.686140,...,0,0,0,1,0,0,0,0,1,0
79997,57.0,79.256140,128.995130,98.742550,107.726430,141.928340,132.398940,57.103550,77.403870,68.931730,...,0,0,0,0,1,0,0,0,0,1
79998,37.0,84.979800,133.152620,94.290375,82.892820,141.696470,107.498764,48.055770,97.403990,69.501526,...,0,0,0,0,1,0,1,0,0,0

In [52]:
X=data.iloc[:,:-2].values
y=data.iloc[:, -1].values

#Splitting into training and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=0)

In [53]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [54]:
data

,AGE,HR_MIN_DAY1,HR_MAX_DAY1,HR_MEAN_DAY1,SYS_BP_MIN_DAY1,SYS_BP_MAX_DAY1,SYS_BP_MEAN_DAY1,DIAS_BP_MIN_DAY1,DIAS_BP_MAX_DAY1,DIAS_BP_MEAN_DAY1,...,ETHNICITY_WHITE_-_EASTERN_EUROPEAN,ETHNICITY_WHITE_-_OTHER_EUROPEAN,ETHNICITY_WHITE_-_RUSSIAN,GENDER_F,GENDER_M,ICU_CCU,ICU_CSRU,ICU_MICU,ICU_SICU,ICU_TSICU
0,21.0,57.207630,108.704030,70.841980,79.847060,119.724170,94.435090,26.880910,68.876540,48.665768,...,0,0,0,1,0,0,0,0,1,0
1,39.0,79.331400,121.138664,96.915726,93.994540,138.594060,113.570206,38.621536,74.270065,66.566760,...,0,0,0,0,1,1,0,0,0,0
2,40.0,118.230290,175.175430,140.936700,122.862610,144.259640,134.501220,67.754650,83.301410,80.350330,...,0,0,0,0,1,0,0,1,0,0
3,75.0,83.780380,89.188980,86.051155,111.390740,144.860570,127.681170,61.139935,75.232390,74.849920,...,0,0,0,0,1,1,0,0,0,0
4,55.0,60.878613,105.637500,80.616840,87.627464,127.758740,99.098860,42.693020,64.015396,64.309480,...,0,0,0,1,0,0,0,1,0,0
5,66.0,40.019630,68.435030,60.395480,97.198326,140.940100,109.457480,43.979748,79.828740,63.191380,...,0,0,0,1,0,0,0,0,0,1
6,88.0,56.889404,98.787170,70.732290,86.096176,159.573210,131.438400,56.737286,98.919030,74.194885,...,0,0,0,0,1,0,0,0,0,1
7,81.0,62.002815,85.822970,84.520810,99.672120,154.289980,125.882450,28.898981,59.936455,44.481770,...,0,0,0,1,0,0,1,0,0,0
8,57.0,89.705830,110.043200,113.968720,115.572910,189.999910,144.896330,44.581734,91.606636,67.561600,...,0,0,0,0,1,0,1,0,0,0
9,90.0,73.032040,102.122310,94.104660,82.418770,121.329730,93.741880,34.476383,55.915947,41.967148,...,0,0,0,0,1,1,0,0,0,0
10,63.0,41.319670,71.347460,52.442623,90.963580,146.204300,110.412430,41.630325,84.953260,57.450000,...,0,0,0,0,1,0,1,0,0,0
11,64.0,101.644070,134.407800,110.352844,79.336730,110.432080,105.360504,36.882175,65.265790,53.860320,...,0,0,0,0,1,0,0,1,0,0
12,55.0,73.463950,88.438340,76.268070,76.257270,139.031650,106.293230,40.091670,86.661090,72.196106,...,0,0,0,0,1,0,0,0,1,0
13,76.0,78.248230,139.058100,110.512910,105.705666,164.979400,125.368400,52.027176,105.721530,78.360610,...,0,0,0,1,0,0,0,0,1,0
14,36.0,66.881220,96.671400,81.779710,90.839030,126.981950,115.341900,38.813335,65.540600,53.805280,...,0,0,0,0,1,0,0,1,0,0
15,37.0,80.773420,103.540230,107.007770,98.777180,141.293950,127.072200,57.954468,82.938095,69.202500,...,0,0,0,1,0,0,1,0,0,0
16,64.0,79.414870,119.652850,99.952910,119.728660,172.254460,138.375210,51.860070,122.840410,71.385086,...,0,0,0,0,1,0,1,0,0,0
17,60.0,51.682550,85.629745,67.373570,99.447495,118.184370,120.174484,32.505920,72.026700,46.775060,...,0,0,0,1,0,0,0,0,0,1
18,90.0,60.492740,104.187450,77.941590,79.155876,186.006500,137.332900,36.059082,79.699940,50.416332,...,0,0,0,0,1,0,0,0,1,0
19,81.0,59.078120,70.426200,61.185905,82.630630,113.507570,95.399980,43.682000,53.666530,46.149635,...,0,0,0,0,1,0,0,0,1,0
20,34.0,98.991170,120.642395,93.795690,51.198875,113.630020,95.707954,33.320465,61.209167,54.182594,...,0,0,0,1,0,0,0,0,1,0
21,55.0,79.767610,111.566345,85.938710,107.014305,170.289660,145.792020,43.720276,68.288230,61.820965,...,0,0,0,1,0,0,0,0,0,1
22,69.0,77.108050,93.200710,86.516770,79.500160,132.892320,108.033676,35.091003,69.385420,60.785103,...,0,0,0,1,0,1,0,0,0,0
23,85.0,64.903530,96.580890,77.680220,97.276436,139.850890,127.166855,47.621178,99.293000,59.442684,...,0,0,0,0,1,0,0,0,0,1
24,44.0,69.077484,96.672290,91.116460,94.860820,150.901890,113.191820,45.150020,132.367030,76.405410,...,0,0,0,1,0,0,0,1,0,0
25,28.0,87.642296,134.623030,106.568710,80.030840,124.121090,107.020830,44.417637,72.552795,61.617940,...,0,0,0,0,1,1,0,0,0,0
26,84.0,78.439354,113.411960,87.992460,84.781624,152.454990,99.413700,56.902267,83.120210,72.047134,...,0,0,0,0,1,0,0,0,0,1
27,57.0,78.071754,112.386720,99.531740,68.227806,117.930340,88.682205,29.009010,73.337320,42.056540,...,0,0,0,0,1,0,0,1,0,0
28,64.0,72.914360,82.820850,84.893166,104.362170,166.758090,122.318085,47.606150,64.586685,55.557260,...,0,0,0,0,1,0,0,0,0,1
29,52.0,103.408170,167.173320,115.460280,66.977745,134.228090,106.490310,33.480194,81.642200,53.959340,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79969,77.0,65.004974,81.170380,63.805458,101.735855,138.423110,117.324110,47.621845,69.419260,57.718430,...,0,0,0,0,1,0,1,0,0,0
79970,79.0,76.098680,132.967160,96.169620,78.420480,118.965760,91.773834,28.709198,60.598156,41.826250,...,0,0,0,1,0,0,0,1,0,0
79971,54.0,69.226110,99.408104,81.294020,123.959430,170.778380,142.631130,58.420727,113.153020,77.973206,...,0,0,0,1,0,0,0,1,0,0
79972,39.0,82.600494,92.711740,94.884420,93.400894,123.672650,102.151750,54.732876,70.854860,59.894950,...,0,0,0,1,0,0,1,0,0,0
79973,88.0,62.056600,94.649020,81.849000,79.345160,127.790450,94.974960,36.040370,60.723076,50.672210,...,0,0,0,1,0,0,0,1,0,0
79974,82.0,85.768680,139.812160,108.483990,87.464450,178.861150,133.074020,53.353775,138.093020,91.029380,...,0,0,0,1,0,0,0,1,0,0
79975,38.0,61.552055,90.395690,82.902510,59.205480,115.060715,92.045100,37.720028,62.568880,53.481520,...,0,0,0,1,0,0,0,1,0,0
79976,87.0,70.973850,99.535540,89.205040,118.066310,108.818340,105.999040,60.905174,66.072770,62.635586,...,0,0,0,0,1,0,0,0,1,0
79977,83.0,53.898520,75.743744,74.494430,118.117230,142.445850,135.433850,54.425987,85.683450,65.936590,...,0,0,0,1,0,0,1,0,0,0
79978,66.0,100.181656,147.515580,119.098560,94.339420,165.260220,124.551090,49.449615,100.067190,78.311480,...,0,0,0,1,0,0,0,1,0,0
79979,71.0,57.584260,83.788086,70.115950,90.495350,155.379430,125.575940,53.610153,103.024600,67.884094,...,0,0,0,0,1,1,0,0,0,0
79980,90.0,72.604034,118.367460,90.445160,105.093790,170.613530,122.055725,39.259274,88.049240,57.085243,...,0,0,0,1,0,0,0,1,0,0
79981,50.0,49.830906,83.378240,58.176370,93.972710,150.715070,126.203780,65.547104,73.743070,64.331510,...,0,0,0,1,0,0,0,0,0,1
79982,70.0,103.120940,110.124670,104.945270,85.572970,134.944430,113.874405,47.145370,80.669980,57.979458,...,0,0,0,0,1,0,0,1,0,0
79983,82.0,80.327170,108.398610,83.052826,89.477350,148.004600,107.927600,28.264824,73.045334,49.039840,...,0,0,0,0,1,0,1,0,0,0
79984,31.0,82.391140,105.209450,92.576890,114.534590,171.781680,146.631740,52.878754,93.323030,70.542330,...,0,0,0,0,1,0,0,0,0,1
79985,40.0,67.079910,112.304290,83.068010,127.167230,129.935910,131.869740,64.635130,107.014700,76.436430,...,0,0,0,0,1,1,0,0,0,0
79986,65.0,75.014885,122.197240,97.442600,98.030365,150.284320,122.432160,50.067455,77.230790,66.038830,...,0,0,0,0,1,0,0,0,1,0
79987,46.0,60.215885,113.693260,88.344420,84.842710,131.043820,109.881040,54.328835,100.503690,74.592160,...,0,0,0,0,1,1,0,0,0,0
79988,80.0,60.669067,99.986640,88.701370,109.735220,156.366700,121.617966,40.035954,82.014694,60.272198,...,0,0,0,0,1,0,0,1,0,0
79989,26.0,52.419620,71.537430,61.549423,93.818436,127.343810,103.136536,30.538132,79.529200,48.255760,...,0,0,0,0,1,0,0,1,0,0
79990,44.0,95.255210,120.259190,105.865400,109.160576,149.261440,129.275100,57.886460,100.431625,77.056076,...,0,0,0,1,0,0,0,0,1,0
79991,58.0,52.078370,95.686160,68.507070,74.252950,129.944500,98.534590,32.176910,69.578110,45.490440,...,0,0,0,0,1,0,1,0,0,0
79992,42.0,54.910847,88.564760,68.762634,123.024220,163.616440,118.623670,43.968536,87.845450,61.533707,...,0,0,0,1,0,0,1,0,0,0
79993,67.0,65.964294,98.301140,79.597786,98.248380,161.336730,135.709900,37.492912,90.884155,57.411150,...,0,0,0,0,1,0,1,0,0,0
79994,76.0,56.035793,97.863950,79.709885,77.546234,120.307580,102.489240,26.716347,49.722248,47.403100,...,0,0,0,1,0,0,1,0,0,0
79995,38.0,55.126850,86.027390,67.647910,83.051470,174.834460,119.396470,40.401726,79.416885,55.099426,...,0,0,0,1,0,0,0,0,0,1
79996,90.0,74.281746,91.267840,91.425380,95.857544,138.798030,130.716320,52.676624,85.140060,65.686140,...,0,0,0,1,0,0,0,0,1,0
79997,57.0,79.256140,128.995130,98.742550,107.726430,141.928340,132.398940,57.103550,77.403870,68.931730,...,0,0,0,0,1,0,0,0,0,1
79998,37.0,84.979800,133.152620,94.290375,82.892820,141.696470,107.498764,48.055770,97.403990,69.501526,...,0,0,0,0,1,0,1,0,0,0

In [55]:
X_train

array([[-2.01844974,  0.63358997,  0.59696917, ..., -0.41365844,
        -0.51740563,  1.36984993],
       [-0.53314251,  0.80529195,  0.71286273, ..., -0.41365844,
        -0.51740563, -0.73000697],
       [-1.41332457, -0.91355308, -0.11274775, ..., -0.41365844,
        -0.51740563,  1.36984993],
       ...,
       [-2.29350663,  0.20175815, -1.13073875, ..., -0.41365844,
        -0.51740563, -0.73000697],
       [-0.47813113, -0.50927759, -1.19653576, ..., -0.41365844,
         1.93271961, -0.73000697],
       [ 1.11719885, -1.39998538, -2.13574423, ...,  2.41745338,
        -0.51740563, -0.73000697]])

In [58]:
#Fitting Logistic Regression to the training set
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

C:\Users\B.K Goel\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [60]:
#predicting the test set results
y_pred = classifier.predict(X_test)
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)

In [70]:
y_pred, y_test

(array([0, 1, 0, ..., 0, 0, 0], dtype=uint8),
 array([0, 1, 0, ..., 0, 0, 0], dtype=uint8))

In [61]:
cm

array([[13091,   701],
       [ 1257,   951]], dtype=int64)

In [62]:
cm.shape

(2, 2)

In [68]:
from sklearn.metrics import accuracy_score
acc_classifier =round(accuracy_score(y_pred, y_test)*100,2)
print(acc_classifier)

87.76

In [ ]:
data2 = pd.read_csv("Dummy.csv")